### ISSUE TITLE
UI improvments for language

### ISSUE THREAD

**Issue by erald14** [erald14/kirin#3]
lets remove the book now button and instead up the language there  , but  not as a menu item ,instead on the top right , nearly close to the edge 

![image](https://user-images.githubusercontent.com/44317405/79512222-4e1d6400-8041-11ea-9785-f11bf4f136d4.png)

and the dropdown can be something like this

**Comment by erald14** [comment]
Make sure it fit good on mobile

**Comment by DanielVafidis** [comment]
I've put it in the menu for the moment to try it when I code the functionality, I'll change it's placement when it works

**Comment by DanielVafidis** [comment]
Added the select in desktop and mobile but still needs polishing (css)

**Comment by DanielVafidis** [comment]
issue reported in second repo
