### ISSUE TITLE
Footer Fixes 

### ISSUE THREAD

**Issue by erald14** [erald14/kirin#4]
1: 
lets make sure the contact us form and  contact info are connected to the same config file as its in the contact page
2: For tags, I want tags to be kind of keywords of what the agency offers.  so create a array of tags in config file ( create a new footer object key parallel to routes and pages and inside the footer object put a tags:["Professional","Good Customer Service"..etc] and then access that from footer and map those tags.
For gallery we have to wait because I haven't decided anything about it .

To start , you need to connect footer component with context.

**Comment by DanielVafidis** [comment]
fixed in second repo
