### ISSUE TITLE
Hotels Arragement

### ISSUE THREAD

**Issue by erald14** [erald14/kirin#5]
So for hotels , fix the double header issue(remove the header call from inside the component) and remove the breadcrumbs section
then arrange routes and links so when you click into a hotel from the main hotels pages it takes to /hotel/:id instead of /hotelbooking 

Also if you notice it , it takes you to the middle of the page instead of the  top (hotel booking)
that can be fixed by adding a scroll to top inside useEffect I think , I cant remember well

**Comment by DanielVafidis** [comment]
done

**Comment by DanielVafidis** [comment]
Done
